### ISSUE TITLE
Building issue in schema.js (Queries/Mutations ... x2)

### ISSUE THREAD

**Issue by VincentMarrec** [lymeo/apollon#52]
When building with simple schema.gql, schema.js duplicates queries and mutations.

Cmd : env PORT=9999 LOG_LEVEL=DEBUG APOLLON_ENV=BUILD node index.js | bunyan

Error : Error: ENOENT: no such file or directory, unlink 'dist/dist/schema.gql'

**Comment by lymeo** [comment]
Please check but should be fixed on latest 2.2.0 version

**Comment by VincentMarrec** [comment]
Problem fixed, thanks you
